# Generated by Django 5.2.8 on 2025-11-14 05:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='試験名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('total_questions', models.IntegerField(default=40, verbose_name='問題数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '試験セット',
                'verbose_name_plural': '試験セット',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='開始時刻')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了時刻')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='得点')),
                ('total_questions', models.IntegerField(verbose_name='総問題数')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了フラグ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('exam_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examset', verbose_name='試験セット')),
            ],
            options={
                'verbose_name': '試験セッション',
                'verbose_name_plural': '試験セッション',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='問題文')),
                ('choice_1', models.CharField(max_length=500, verbose_name='選択肢1')),
                ('choice_2', models.CharField(max_length=500, verbose_name='選択肢2')),
                ('choice_3', models.CharField(max_length=500, verbose_name='選択肢3')),
                ('choice_4', models.CharField(max_length=500, verbose_name='選択肢4')),
                ('correct_answer', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='正解番号')),
                ('explanation', models.TextField(verbose_name='解説')),
                ('explanation_1', models.TextField(verbose_name='選択肢1の説明')),
                ('explanation_2', models.TextField(verbose_name='選択肢2の説明')),
                ('explanation_3', models.TextField(verbose_name='選択肢3の説明')),
                ('explanation_4', models.TextField(verbose_name='選択肢4の説明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.examset', verbose_name='試験セット')),
            ],
            options={
                'verbose_name': '問題',
                'verbose_name_plural': '問題',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.IntegerField(verbose_name='問題順序')),
                ('user_answer', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='ユーザーの解答')),
                ('is_correct', models.BooleanField(verbose_name='正解フラグ')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='解答時刻')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.examsession', verbose_name='試験セッション')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question', verbose_name='問題')),
            ],
            options={
                'verbose_name': '解答',
                'verbose_name_plural': '解答',
                'ordering': ['question_order'],
            },
        ),
    ]
